#!/bin/bash

MINPARAMS=1

if [ $# -lt "$MINPARAMS" ]; then
  echo -e "Usage: $0 <ambari-profile-name>\n"
  exit 0
fi

ProfileName=$1
ProfilePath="profiles/ambari/${ProfileName}.profile"
BlueprintPath="profiles/ambari/${ProfileName}.blueprint"
HostmapPath="profiles/ambari/${ProfileName}.hostmap"

if [[ ! -f $ProfilePath ]]; then
  echo "Profile ${ProfileName} not found. Exiting."
  exit 0
fi
if [[ ! -f $BlueprintPath ]]; then
  echo "Blueprint ${ProfileName} not found. Exiting."
  exit 0
fi
if [[ ! -f $HostmapPath ]]; then
  echo "Hostmap ${ProfileName} not found. Exiting."
  exit 0
fi
echo "Provisioning ${ProfileName} Ambari cluster"

if [ -L current.profile ]; then
  rm -f current.profile
fi
ln -s $ProfilePath current.profile

vagrant up

# Allow last VM to register with Ambari Server
#  (this needs tuning, or a better workaround)
sleep 60

echo -n "Applying ${ProfileName} Ambari blueprint..."
curl --user admin:admin -H 'X-Requested-By:mycompany' -X POST http://gw.example.com:8080/api/v1/blueprints/hdp-blueprint -d @${BlueprintPath}
curl --user admin:admin -H 'X-Requested-By:mycompany' -X POST http://gw.example.com:8080/api/v1/clusters/hdp-cluster -d @${HostmapPath}

ProgressPercent=`curl -s --user admin:admin -H 'X-Requested-By:mycompany' -X GET http://gw.example.com:8080/api/v1/clusters/hdp-cluster/requests/1 | grep progress_percent | awk '{print $3}' | cut -d . -f 1`
echo " Progress: $ProgressPercent %"

while [[ `echo $ProgressPercent | grep -v 100` ]]; do
  ProgressPercent=`curl -s --user admin:admin -H 'X-Requested-By:mycompany' -X GET http://gw.example.com:8080/api/v1/clusters/hdp-cluster/requests/1 | grep progress_percent | awk '{print $3}' | cut -d . -f 1`
  tput cuu1
  echo " Progress: $ProgressPercent %"
  sleep 2
done

echo ""
echo "Cluster build is complete."
echo "You may access the Ambari web interface at http://gw.example.com:8080"
echo "User/pass: admin / admin"
echo ""
